name: TheBegining
favicon: null
layout_spectrum: 0.94134
typography_spectrum: 0.2432
title: where does it go
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0301'
    - '#6b645e'
    - '#443a31'
    - '#c4c4c2'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
