name: TheBegining
favicon: null
layout_spectrum: 0.70861782040447
typography_spectrum: 0.6223788897041231
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0301'
    - '#6b645e'
    - '#443a31'
    - '#c4c4c2'
  brandStrength: 0.625
  lightness: 0.6623993017710745
  saturation: 0.9222953356802464
  rhythmicContrast: 0.7574514602310956
purpose: []
